version: '3.8'

services:
  zabbix-mysql:
    image: mysql:8.0
    container_name: zabbix-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    volumes:
      - zbx_mysql:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-authentication-plugin=mysql_native_password

  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    container_name: zabbix-server
    restart: always
    ports:
      - "10051:10051"
    environment:
      DB_SERVER_HOST: zabbix-mysql
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: zabbix
      MYSQL_DATABASE: zabbix
    depends_on:
      - zabbix-mysql

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    container_name: zabbix-agent
    restart: always
    privileged: true
    pid: "host"
    network_mode: "host"
    environment:
      ZBX_HOSTNAME: "DevOps-Host"
      ZBX_SERVER_HOST: "127.0.0.1"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
       - grafana_data:/var/lib/grafana

volumes:
  zbx_mysql:
  grafana_data: